
/*ENDEREÇO DA EMPRESA*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-ENDERECO', 'RUA Qualquer', 1);
                   
/*ENDEREÇO DA EMPRESA - NUMERO*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-NUMERO', '1234', 1);  
                  
/*CIDADE DA EMPRESA*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-CIDADE', 'Curitiba', 1);      
  
/*UF DA EMPRESA*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-UF', 'PR', 1);   
                  

/*CNPJ DA EMPRESA*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-CGC', '02.267.245/0001-05', 1);                     
                                    
/*CODIGO IBGE DA CIDADE DA EMPRESA*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-CIDADE-CODIGO', '4106902', 1); 
 
/*TELEFONE DA EMPRESA*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-TELEFONE', '(00) 0000-0000', 1); 
                  
/*EMAIL DA EMPRESA*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-EMAIL', 'email@empresa.com.br', 1);    
                  
                  
/*LOCAL DOS ARQUIVOS SPED*/
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-LOCAL-ARQUIVOS', 'C:\', 1);        