/*Configuração de Regime de apuração - PIS/COFINS*/


INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-COD-INC-TRIB', '2', 1);


INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-IND-APRO-CRED', '1', 1);

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-COD-TIPO-CONT', '1', 1);   
 
INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-IND-REG-CUM', '9', 1);  