
/*INSERE NOVOS PARAMETROS PARA FILIAL 1 */

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-TIPO-ATIV', '1', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-INSC_MUNICIPAL', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-INSC_ESTADUAL', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-EMAIL', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-NOME', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-NOME_FANTASIA', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'EMPRESA-BAIRRO', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-FISCAL-PERFIL', 'A', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-FISCAL-PERIODO-IPI', 'M', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-EMAIL', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-NOME', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-CPF-CNPJ', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-CRC', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-CEP', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-ENDERECO', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-NUMERO_END', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-COMPL_END', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-BAIRRO', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-FONE', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-FAX', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-CONTADOR-CID_COD_IBGE', '', :P_FILIAL);
COMMIT WORK;

INSERT INTO CONFIG (CHAVE_CONFIG, SECAO_CAMPO, CONTEUDO, FILIAL) VALUES
                   ((SELECT COALESCE(MAX(CHAVE_CONFIG),0) + 1 FROM CONFIG), 'SPED-LOCAL-ARQUIVOS', 'C:\', :P_FILIAL);
COMMIT WORK;




